#:schema https =//raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = "{{.HostName}}"

[[blocks]]
  type = "prompt"
  alignment = "left"

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "red"
    template = "┏["

  [[blocks.segments]]
    type = "os"
    style = "plain"
    foreground = "white"
    template = "{{ if .WSL }}WSL at {{ end }}{{.Icon}} "

  [[blocks.segments]]
    type = "session"
    style = "plain"
    foreground = "white"
    template = "{{ if .SSHSession }} {{ end }}{{ .UserName }}"

    [blocks.segments.properties]
      display_host = false

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "red"
    template = "]"

  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "green"
    template = "<red>[</>{{if .UpstreamIcon }}{{ .UpstreamIcon }}{{else}} {{end}}{{if gt .Behind 0}} {{end}}{{if gt .Ahead 0}} {{end}}{{ .HEAD }}{{if or (.Working.Changed) (.Staging.Changed)}} {{end}}<red>]</>"

    [blocks.segments.properties]
      fetch_status = true
      fetch_upstream_icon = true
      branch_icon = ""
      commit_icon = '@'

  [[blocks.segments]]
    type = "root"
    style = "plain"
    foreground = "white"
    template = "<red>[</><red>]</>"

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "darkGray"
    template = "<red>[</>{{ .FormattedMs }}<red>]</>"

    [blocks.segments.properties]
      threshold = 500
      style = "round"

  [[blocks.segments]]
    type = "exit"
    style = "plain"
    foreground = "red"
    template = "[{{ if gt .Code 0 }} {{ .Meaning }}{{ else }}{{ end }}]"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "lightWhite"
    template = "<red>┖[</>{{ .Path }}<red>]></>"

    [blocks.segments.properties]
      style = "full"

      [blocks.segments.properties.mapped_locations]
        "C:\\Projects\\csharp" = "\uf81a ="
        "C:\\Projects\\gfx" = "\uf03e ="
        "C:\\Projects\\lua" = "\ue620 ="
        "C:\\Projects\\minecraft" = "\uf872 ="
        "C:\\Projects\\misc" = "\ue796 ="
        "C:\\Projects\\php" = "\ue73d ="
        "C:\\Projects\\python" = "\uf81f ="
